Keyed/Alerts.xml
Keyed/Dates.xml
Keyed/Designators.xml
Keyed/Enums.xml
Keyed/Incidents.xml
Keyed/Letters.xml
Keyed/Messages.xml
Keyed/Misc_Gameplay.xml
Keyed/ScenParts.xml
Keyed/Time.xml

All Keyed strings are now up to date.

Improve Keyed translations

---

DefInjected/ChemicalDef/Smokeleaf.xml
DefInjected/HediffDef/Smokeleaf.xml
DefInjected/NeedDef/Smokeleaf.xml
DefInjected/RecipeDef/Recipes_Add.xml
DefInjected/ThingDef/Buildings_Production.xml
DefInjected/ThingDef/Items_Resource_RawPlant.xml
DefInjected/ThingDef/Plants_Cultivated_Farm.xml
DefInjected/ThingDef/Smokeleaf.xml
DefInjected/ThoughtDef/Smokeleaf.xml
Keyed/Dialog_StatsReports.xml
Keyed/Menus_Main.xml
Keyed/Misc_Gameplay.xml

Fix Smokeleaf

---

Keyed/Skills.xml

re-translate some obscured wording from english.

re-translate some obscured wording

---

Keyed/Alerts.xml
Keyed/Dialogs_Various.xml
Keyed/FloatMenu.xml
Keyed/GameplayCommands.xml
Keyed/ITabs.xml
Keyed/Letters.xml
Keyed/MainTabs.xml
Keyed/Menu_Options.xml
Keyed/Menus_Main.xml
Keyed/Messages.xml
Keyed/Misc.xml
Keyed/Misc_Gameplay.xml

[A16] Translation

---

Backstories/Backstories.xml

修正背景故事的翻译错误

---

Backstories/Backstories.xml

polish content from the line 500 to 700

polish content from the line 500 to 700

---

Backstories/Backstories.xml

Modify a backstory and fix a XML tag error.

Modify a backstory and fix a XML tag error.

---

Backstories/Backstories.xml

Added more translation for Backstories

---

DefInjected/BillRepeatModeDef/BillRepeatModeDefs.xml
DefInjected/BillStoreModeDef/BillStoreModeDefs.xml
DefInjected/InstructionDef/Instructions.xml
DefInjected/ThingDef/Plants_Wild_Arid.xml
DefInjected/ThingDef/Plants_Wild_General.xml
DefInjected/ThingDef/Plants_Wild_Swamp.xml
DefInjected/ThingDef/Plants_Wild_Tropical.xml
DefInjected/WorkGiverDef/WorkGivers.xml
DefInjected/WorkTypeDef/WorkTypes.xml

Signed-off-by: Sefank <sefank@foxmail.com>

Update some description and fix some missing translations. 

---

DefInjected/RulePackDef/RulePacks_Combat.xml
DefInjected/RulePackDef/RulePacks_Damage.xml
DefInjected/RulePackDef/RulePacks_DamageEvent.xml

translate combat, damage and damage event of rule packs.

translate combat, damage and damage event of rule packs.

---

DefInjected/IncidentDef/Incidents_World_Quests.xml

fix typo 无限电 -> 无线电

---

Ideology/DefInjected/MemeDef/Memes_GenderSupremacy.xml
Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
Ideology/DefInjected/MemeDef/Memes_Individualism.xml
Ideology/DefInjected/MemeDef/Memes_Misc.xml
Ideology/DefInjected/MemeDef/Memes_Primacy.xml
Ideology/DefInjected/MemeDef/Memes_Structures_Basic.xml
Ideology/DefInjected/MemeDef/Memes_Structures_OriginsReligious.xml

修正memedef的词根

---

Biotech/DefInjected/BodyPartDef/BodyParts_Mechanoid.xml
Biotech/DefInjected/BodyPartGroupDef/BodyPartGroups.xml
Biotech/DefInjected/BossgroupDef/Bossgroups.xml
Biotech/DefInjected/HediffDef/Hediffs_Mechanitor.xml
Biotech/DefInjected/HediffDef/Hediffs_Mechs.xml
Biotech/DefInjected/PawnKindDef/Races_Mechanoids_Heavy.xml
Biotech/DefInjected/PawnKindDef/Races_Mechanoids_Light.xml
Biotech/DefInjected/PawnKindDef/Races_Mechanoids_Medium.xml
Biotech/DefInjected/PawnKindDef/Races_Mechanoids_SuperHeavy.xml
Biotech/DefInjected/ThingDef/Hediffs_Mechanitor.xml

form SeaN-2

---

Biotech/DefInjected/RecipeDef/Recipes_MechGestator_Heavy.xml
Biotech/DefInjected/RecipeDef/Recipes_MechGestator_Light.xml
Biotech/DefInjected/RecipeDef/Recipes_MechGestator_Medium.xml
Biotech/DefInjected/RecipeDef/Recipes_MechGestator_SuperHeavy.xml
Biotech/DefInjected/RecipeDef/Recipes_MechResurrection.xml
Biotech/DefInjected/RulePackDef/Interactions_Social.xml
Biotech/DefInjected/RulePackDef/RulePacks_Namers_Faction.xml
Biotech/DefInjected/RulePackDef/RulePacks_Namers_Mechs.xml
Biotech/DefInjected/ThingDef/Apparel_Mech.xml

from SeaN-3

---

Biotech/DefInjected/ThoughtDef/Thoughts_Situation_Special.xml

憎恶毒蜂的小小的润色

---

Core/Keyed/FloatMenu.xml

"without medicine"

---

Royalty/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml

Honorable == 荣誉体面 -> 荣耀的
Grandiose == 宏伟非凡-> 隆重的
Unimpressive == 平平无奇 -> 不起眼的
---
https://github.com/Ludeon/RimWorld-ChineseSimplified/blob/03b55205212a6d227d1b3049c51ee35db3871878/Royalty/DefInjected/ThoughtDef/Thoughts_Memory_Rituals.xml#L4-L5
https://github.com/Ludeon/RimWorld-ChineseSimplified/blob/03b55205212a6d227d1b3049c51ee35db3871878/Royalty/DefInjected/ThoughtDef/Thoughts_Memory_Rituals.xml#L9-L10
https://github.com/Ludeon/RimWorld-ChineseSimplified/blob/03b55205212a6d227d1b3049c51ee35db3871878/Royalty/DefInjected/ThoughtDef/Thoughts_Memory_Rituals.xml#L19-L20

Consistency principle

---

Core/DefInjected/ThingDef/Items_Resource_Stuff.xml

Abbreviation of steel

---

Biotech/Keyed/Letters.xml

补充植入异种胚芽时的弹出的描述文本

---

Biotech/DefInjected/ThingDef/Items_Resource_Manufactured.xml

lable capitalization
